<?php

declare(strict_types=1);

/*
 * This file is part of the project by AGBOKOUDJO Franck.
 *
 * (c) AGBOKOUDJO Franck <internationaleswebservices@gmail.com>
 * Company: INTERNATIONALES WEB APPS & SERVICES
 */

namespace Wlindabla\MailingBundle\Mailing;

use Wlindabla\MailingBundle\Mailing\MailerManagerInterface;
use Wlindabla\MailingBundle\Mailing\SupportMailer;
use Wlindabla\MailingBundle\Mailing\SystemMailer;

/**
 * Centralized manager for handling company emails.
 *
 * This class orchestrates the use of SystemMailer and SupportMailer to isolate
 * business logic from sending technical details.
 *
 * @author AGBOKOUDJO Franck <internationaleswebservices@gmail.com>
 * @package App\Infrastructure\Service\Mailing
 */
final class MailerManagerEntreprise implements MailerManagerInterface
{
    /**
     * @param SystemMailer $systemMailer Automated sending service linked to the 'system' transport (noreply).
     * @param SupportMailer $supportMailer Sending service linked to the 'support' transport (file management, clients, and management).
     */
    public function __construct(
        private readonly SystemMailer $systemMailer,
        private readonly SupportMailer $supportMailer,
    ) {}

    /**
     * Sends an automated notification generated by the application to a user.
     *
     * **When to use it?**
     * Use exclusively for automated platform actions where the user does not need
     * to reply directly to the email (sender: `noreply-systeme@iwas.net`).
     * *Examples:* Account activation, password reset, security alerts.
     *
     * @param string|array $recipientAddress Email address or array of recipient user addresses.
     * @param string $subject Email subject (must not be empty).
     * @param string $templatePath Path to the Twig template (e.g., 'email/security/reset_password.html.twig').
     * @param array $context Key-value array containing variables to pass to the Twig template.
     * @param int $priority Email priority level (1 = Critical, 5 = Low). Defaults to standard (3).
     *
     * @example
     * ```php
     * $this->mailerManager->notifyBySystem(
     *     'jean.dupont@gmail.com',
     *     'Activation of your eQapitalise account',
     *     'email/register_confirmation.html.twig',
     *     ['user' => $user, 'token' =>$token],
     *     PriorityInterface::PRIORITY_HIGH
     * );
     * ```
     */
    public function notifyBySystem(
        string|array $recipientAddress,
        string $subject,
        string $templatePath,
        array $context,
        int $priority = PriorityInterface::PRIORITY_NORMAL
    ): void {
        $this->systemMailer->send(
            $recipientAddress,
            $subject,
            $templatePath,
            $context,
            $priority
        );
    }

    /**
     * Notifies management or an internal department (secretariat) following an action taken by a client.
     *
     * **When to use it?**
     * Use when the application needs to alert management that an event occurred on the website
     * (e.g., a filled form, a deposited file). The advantage here is that by setting `$clientEmail`
     * in the 'Reply-To' field, management can reply to the client with a single click from their email client (Outlook, Gmail).
     * *Example:* Notification of a new manuscript deposit with the PDF file attached.
     *
     * @param string|array $directionEmail The internal address receiving the alert (e.g., 'secretariat@iwas.net' or 'direction@iwas.net').
     * @param string $subject The title of the notification received by the manager.
     * @param string $htmlTemplate Path to the Twig template displaying the summary of the client's data.
     * @param array|null $context Event data or submission entity to pass to the Twig template.
     * @param string|null $clientEmail Email address of the client originating the action (assigned to Reply-To).
     * @param array|null $attachments Array of attachments in the form ['file/path' => 'File_Name.pdf'].
     *
     * @example
     * ```php
     * $this->mailerManager->notifyToDirection(
     *     'secretariat@iwas.net',
     *     'New manuscript submission',
     *     'email/notification_submission.html.twig',
     *     ['submission' => $manuscriptSubmission],
     *     $manuscriptSubmission->getEmail(), // client email
     *     ['/var/uploads/doc.pdf' => 'Manuscript_Author.pdf']
     * );
     * ```
     */
    public function notifyToDirection(
        string|array $directionEmail,
        string $subject,
        string $htmlTemplate,
        ?array $context = null,
        ?string $clientEmail = null,
        ?array $attachments = []
    ): void {
        $this->supportMailer->send(
            recipientEmail: $directionEmail,
            subject: $subject,
            htmlTemplate: $htmlTemplate,
            context: $context,
            senderEmail: null, // Uses the default config address for the 'support' transport
            replyToEmail: $clientEmail, // Allows management to reply directly to the client
            attachments: $attachments
        );
    }

    /**
     * Sends an official email signed by management/support to an external client or user.
     *
     * **When to use it?**
     * Use during outgoing exchanges initiated by management or by an administrative application action
     * intended to formally notify a third party. The displayed sender will be the professional address (e.g., `support@iwas.net`).
     * *Examples:* Sending a deposit certificate, manuscript acceptance/rejection, sending an invoice.
     *
     * @param string|array $recipientEmail Email address of the external user or client (recipient).
     * @param string $subject Subject of the message received by the client.
     * @param string $htmlTemplate Path to the Twig template for the official message.
     * @param array|null $context Personalization variables for the message (e.g., client name, motives).
     * @param string|null $replyToEmail Optional: Alternative reply address if necessary.
     * @param array|null $attachments Optional: Official attached files sent to the client (e.g., Signed_Contract.pdf).
     *
     * @example
     * ```php
     * $this->mailerManager->sendMailByDirection(
     *     'external-client@gmail.com',
     *     'Validation of your manuscript - IWAS',
     *     'email/client_manuscript_validation.html.twig',
     *     ['client' => $client, 'comments' =>$evaluationData],
     *     null,
     *     ['/path/to/attestation.pdf' => 'Receipt_Certificate.pdf']
     * );
     * ```
     */
    public function sendMailByDirection(
        string|array $recipientEmail,
        string $subject,
        string $htmlTemplate,
        ?array $context = null,
        ?string $replyToEmail = null,
        ?array $attachments = []
    ): void {
        $this->supportMailer->send(
            recipientEmail: $recipientEmail,
            subject: $subject,
            htmlTemplate: $htmlTemplate,
            context: $context,
            senderEmail: null, // Default sender: support@iwas.net
            replyToEmail: $replyToEmail,
            attachments: $attachments
        );
    }
}